apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tracker-app-proj
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - 'https://stackapporg@dev.azure.com/stackapporg/trackeraks/_git/trackerapp-k8s-manifests'