apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracker-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: img-alias=trackeracrregauseastdev.azurecr.io/tracker/trackerrepo:*
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/azuredeveops-repo-pipeline
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/img-alias.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://stackapporg@dev.azure.com/stackapporg/trackeraks/_git/trackerapp-k8s-manifests
    targetRevision: main
    path: env/dev
    #path: base-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false